import React, { useState } from 'react'
import { useAuth } from './hooks/useAuth'
import Login from './components/Login'
import TokenManager from './components/TokenManager'
import UserManager from './components/UserManager'
import WorkflowManager from './components/WorkflowManager'

// We will use standard Tailwind classes on Box to maintain the design
// until the Gluestack components are fully generated by the CLI.
import { Box } from './components/ui/box'
import { Text } from './components/ui/text'
import { Heading } from './components/ui/heading'
import { Button, ButtonText, ButtonIcon } from './components/ui/button'
import { HStack } from './components/ui/hstack'
import { VStack } from './components/ui/vstack'
import { Icon } from './components/ui/icon'

function Centered({ children }) {
  return (
    <Box className="min-h-screen flex items-center justify-center px-4 text-center">
      {children}
    </Box>
  )
}

export default function App() {
  const { session, profile, profileError, loading, isAdmin, loginWithGoogle, logout } = useAuth()
  const [tab, setTab] = useState('tokens')

  if (loading) {
    return <Centered><Text className="text-gray-500 animate-pulse">Loading admin console…</Text></Centered>
  }

  if (!session) {
    return <Login onLogin={loginWithGoogle} />
  }

  if (profileError) {
    return (
      <Centered>
        <Box className="max-w-md bg-[#1a1c23] border border-yellow-900/30 rounded-2xl p-8">
          <Heading size="xl" className="font-bold text-white mb-2">Backend Unreachable</Heading>
          <Text className="text-gray-400 text-sm">
            Could not verify your account with the API server.
          </Text>
          <Text className="text-yellow-400/80 mt-3 text-xs font-mono break-all">{profileError}</Text>
          <HStack space="lg" className="mt-6 justify-center">
            <Button variant="link" onPress={() => window.location.reload()}>
              <ButtonText className="text-blue-400">Retry</ButtonText>
            </Button>
            <Button variant="link" onPress={logout}>
              <ButtonText className="text-gray-400">Sign out</ButtonText>
            </Button>
          </HStack>
        </Box>
      </Centered>
    )
  }

  if (!isAdmin) {
    return (
      <Centered>
        <Box className="max-w-md bg-[#1a1c23] border border-red-900/30 rounded-2xl p-8">
          <Heading size="xl" className="font-bold text-white mb-2">Access Denied</Heading>
          <Text className="text-gray-400 text-sm">
            The account <Text bold className="text-gray-200">{profile?.email || session.user?.email}</Text> is not an administrator.
            Ask an existing admin to grant you access, then reload.
          </Text>
          <Button variant="link" onPress={logout} className="mt-6">
            <ButtonText className="text-blue-400">Sign out</ButtonText>
          </Button>
        </Box>
      </Centered>
    )
  }

  return (
    <Box className="min-h-screen bg-[#03060D] text-slate-300 font-sans selection:bg-cyan-500/30">
      <Box className="fixed inset-0 bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-cyan-900/10 via-[#03060D] to-[#03060D] pointer-events-none" />
      
      <Box className="border-b border-cyan-900/30 bg-[#050B14]/80 backdrop-blur-xl sticky top-0 z-20 shadow-[0_4px_30px_rgba(0,0,0,0.5)]">
        <HStack className="max-w-6xl mx-auto px-4 py-4 justify-between items-center">
          <HStack space="md" className="items-center">
            <Box className="w-10 h-10 rounded-xl bg-gradient-to-br from-cyan-600 to-blue-700 flex items-center justify-center shadow-[0_0_20px_rgba(6,182,212,0.3)] border border-cyan-400/30">
              <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" /></svg>
            </Box>
            <VStack>
              <Heading size="md" className="font-bold text-transparent bg-clip-text bg-gradient-to-r from-white to-cyan-200 leading-tight tracking-wide">CamTech Admin</Heading>
              <Text size="xs" className="font-medium text-cyan-500/70">{profile?.email}</Text>
            </VStack>
          </HStack>
          <HStack space="xl" className="items-center">
            <HStack className="bg-[#0B1221] rounded-xl p-1 border border-cyan-900/40 shadow-inner">
              <Button
                variant="link"
                onPress={() => setTab('tokens')}
                className={`px-6 py-2 rounded-lg transition-all duration-300 ${tab === 'tokens' ? 'bg-cyan-500/20 border border-cyan-500/30 shadow-[0_0_15px_rgba(6,182,212,0.15)]' : 'hover:bg-white/5 border border-transparent'}`}
              >
                <ButtonText className={`text-sm font-bold ${tab === 'tokens' ? 'text-cyan-300' : 'text-slate-500 hover:text-slate-300'}`}>Access Tokens</ButtonText>
              </Button>
              <Button
                variant="link"
                onPress={() => setTab('users')}
                className={`px-6 py-2 rounded-lg transition-all duration-300 ${tab === 'users' ? 'bg-cyan-500/20 border border-cyan-500/30 shadow-[0_0_15px_rgba(6,182,212,0.15)]' : 'hover:bg-white/5 border border-transparent'}`}
              >
                <ButtonText className={`text-sm font-bold ${tab === 'users' ? 'text-cyan-300' : 'text-slate-500 hover:text-slate-300'}`}>Users</ButtonText>
              </Button>
              <Button
                variant="link"
                onPress={() => setTab('automations')}
                className={`px-6 py-2 rounded-lg transition-all duration-300 ${tab === 'automations' ? 'bg-orange-500/20 border border-orange-500/30 shadow-[0_0_15px_rgba(251,146,60,0.15)]' : 'hover:bg-white/5 border border-transparent'}`}
              >
                <ButtonText className={`text-sm font-bold ${tab === 'automations' ? 'text-orange-300' : 'text-slate-500 hover:text-slate-300'}`}>Automations</ButtonText>
              </Button>
            </HStack>
            <Button variant="link" onPress={logout} className="flex items-center gap-2">
              <ButtonText className="text-sm font-bold text-slate-500 hover:text-red-400 transition-colors duration-300">Sign out</ButtonText>
              <svg className="w-4 h-4 text-slate-500 hover:text-red-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" /></svg>
            </Button>
          </HStack>
        </HStack>
      </Box>

      <Box className="relative max-w-6xl mx-auto px-4 py-10 z-10">
        {tab === 'tokens' ? <TokenManager /> : tab === 'users' ? <UserManager /> : <WorkflowManager />}
      </Box>
    </Box>
  )
}
