name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server
        run: |
          echo "Syncing files to CamTech directory..."
          rsync -a --exclude '.git' ./ /home/ubuntu-server/CamTech/
          
          echo "Rebuilding and restarting Docker..."
          cd /home/ubuntu-server/CamTech
          echo "pTT!CT01" | sudo -S docker compose up -d --build
          echo "Deployment complete!"
